import { api } from "~/utils/api"
import { useUser } from "@clerk/nextjs"
import { type NextPage } from "next"
import Head from "next/head"

const SinglePost: NextPage = () => {
    const { isLoaded: userLoaded, isSignedIn } = useUser()

    // Start fetching asap
    api.posts.getAll.useQuery()

    // return empty div if BOTH aren't loaded, since user tends to load faster
    if (!userLoaded) return <div />

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex h-screen justify-center">
                <div>SinglePost View</div>
            </main>
        </>
    )
}

export default SinglePost
