import { type NextPage } from "next"
import Head from "next/head"
import { api } from "~/utils/api"
import CreatePostWizard from "./post-wizard"
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs"
import PostView from "./post-view"

const Home: NextPage = () => {
    const { data, isLoading } = api.posts.getAll.useQuery()

    const user = useUser()

    if (isLoading) return <>Loading...</>
    if (!data) return <>Something went wrong.</>

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex h-screen justify-center">
                <div className="h-full w-full border-x border-slate-400 bg-slate-900 md:max-w-2xl ">
                    <div className="flex justify-end border-b border-slate-400 p-4">
                        {!user.isSignedIn && <SignInButton />}
                        {!!user.isSignedIn && <SignOutButton />}
                    </div>
                    <div className="flex border-b border-slate-400 p-4">
                        <SignIn
                            path="/sign-in"
                            routing="path"
                            signUpUrl="/sign-up"
                        />
                        <CreatePostWizard />
                    </div>
                    <div className="flex flex-col">
                        {...data?.map((fullPost) => (
                            <PostView key={fullPost.post.id} {...fullPost} />
                        ))}
                    </div>
                </div>
            </main>
        </>
    )
}

export default Home
