import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import CreatePostWizard from "./post-wizard";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  
  const { data, isLoading } = api.posts.getAll.useQuery();

  const user = useUser();

  if (isLoading) return <>Loading...</>
  if (!data) return <>Something went wrong.</>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="bg-slate-900 w-full md:max-w-2xl border-x border-slate-400 h-full ">
          {/* CODE */}
          <div className="flex justify-end border-b p-4 border-slate-400">
              {!user.isSignedIn && <SignInButton/> }
              {!!user.isSignedIn && <SignOutButton/> }
            </div>
          <div className="flex border-b border-slate-400 p-4">
            <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
            <CreatePostWizard />
          </div>
          <div className="flex flex-col">
            {
              ...data?.map((post) => (
                <div key={post.id} className="flex border-b border-slate-400 p-8 justify-center">
                  {post.content}
                </div>
              ))
            }
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
